# Generated by Django 5.2.4 on 2025-07-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice', '0002_alter_call_options_rename_started_at_call_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_sid',
            field=models.CharField(max_length=100),
        ),
    ]
